import Head from "next/head";
import Hero from "components/hero/hero";
import heroData from "component-data/hero-data";
import Button from "components/button/button";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Fishing Reports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Hero
          title={heroData.title}
          copy={heroData.copy}
          sectionClass={heroData.sectionClass}
          headerClass={heroData.headerClass}
          imageSource={heroData.imageSource}
        >
          <Button copy="Click me" />
        </Hero>
      </main>
    </div>
  );
}
